root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  kill_delay = "0s"

[misc]
  clean_on_exit = true
